/*
 * PURPOSE:
 *   Defines the `Embedder` trait for generating vector embeddings from text.
 *   Abstracts the underlying inference engine (Ollama, OpenAI, Candle, etc.).
 *
 * REQUIREMENTS:
 *   - Must support single and batch embedding generation
 *   - Must be async and thread-safe
 *   - Must return standard `Vec<f32>` vectors
 *
 * IMPLEMENTATION RULES:
 *   1. Use `async_trait` macro
 *   2. Return `anyhow::Result` for error handling
 *
 * USAGE:
 *   let embedder = MyEmbedder::new();
 *   let vector = embedder.embed("hello world").await?;
 */

use anyhow::Result;
use async_trait::async_trait;

#[async_trait]
pub trait Embedder: Send + Sync {
    /// Generate embedding for a single text string
    async fn embed(&self, text: &str) -> Result<Vec<f32>>;

    /// Generate embeddings for a batch of texts
    /// Default implementation iterates singly, but backends should override for batch efficiency
    async fn embed_batch(&self, texts: &[String]) -> Result<Vec<Vec<f32>>> {
        let mut vectors = Vec::with_capacity(texts.len());
        for text in texts {
            vectors.push(self.embed(text).await?);
        }
        Ok(vectors)
    }

    /// Return the dimension of the vectors generated by this embedder
    async fn dimension(&self) -> Result<usize>;

    /// Return the name of the model being used (e.g. "fastembed:AllMiniLML6V2", "ollama:nomic-embed-text")
    fn model_name(&self) -> String;
}
