/*
 * PURPOSE:
 *   Defines the `Embedder` trait for generating vector embeddings from text.
 *   Abstracts the underlying inference engine (Ollama, OpenAI, Candle, etc.).
 *
 * REQUIREMENTS:
 *   - Must support single and batch embedding generation
 *   - Must be async and thread-safe
 *   - Must return standard `Vec<f32>` vectors
 *
 * IMPLEMENTATION RULES:
 *   1. Use `async_trait` macro
 *   2. Return `anyhow::Result` for error handling
 *
 * USAGE:
 *   let embedder = MyEmbedder::new();
 *   let vector = embedder.embed("hello world").await?;
 */

use crate::resource::Resource;
use anyhow::Result;
use async_trait::async_trait;

#[async_trait]
pub trait Embedder: Send + Sync {
    /// Generate embedding for a single text string with an optional target dimension.
    async fn embed(&self, text: &str, target_dim: Option<usize>) -> Result<Vec<f32>>;

    /// Generate embeddings for a batch of texts with an optional target dimension.
    async fn embed_batch(
        &self,
        texts: &[String],
        target_dim: Option<usize>,
    ) -> Result<Vec<Vec<f32>>> {
        let mut vectors = Vec::with_capacity(texts.len());
        for text in texts {
            vectors.push(self.embed(text, target_dim).await?);
        }
        Ok(vectors)
    }

    /// Return the native dimension of the vectors generated by this embedder
    async fn dimension(&self) -> Result<usize>;

    /// Return the name of the model being used (e.g. "fastembed:AllMiniLML6V2", "ollama:nomic-embed-text")
    fn model_name(&self) -> String;

    /// Release any heavyweight resources held by this embedder (e.g. GPU model weights).
    ///
    /// Called by the server's idle-eviction watchdog. After release, the next embed()
    /// call must succeed by reloading lazily — implementations that hold no such
    /// resources can use the default no-op.
    ///
    /// Must be idempotent and safe to call concurrently with embed().
    fn release(&self) {}

    /// The physical / logical resources this embedder needs to perform an embed
    /// call. Used by `ResourceArbiter` to ensure concurrent embed calls only
    /// contend on resources they actually share.
    ///
    /// Default: empty — meaning "no arbitration needed" (e.g. mock/test
    /// embedders). Real backends MUST override this so the arbiter can do its
    /// job. Returning `[]` from a production embedder is correct only if the
    /// embedder genuinely has no shared resource (rare).
    fn required_resources(&self) -> Vec<Resource> {
        Vec::new()
    }
}

/// Helper to L2-normalize a vector in place
pub fn l2_normalize(vec: &mut [f32]) {
    let sum_sq: f32 = vec.iter().map(|x| x * x).sum();
    let norm = sum_sq.sqrt();
    if norm > 0.0 {
        for x in vec.iter_mut() {
            *x /= norm;
        }
    }
}
